### ISSUE TITLE
Add | as term to search all

### ISSUE THREAD

**Issue by 0Raik** [G-dH/extensions-search-provider#1]
Thanks so much for such a nice extension. Incredibly useful and can't imagine why this is not part of Gnome already. Thanks for solving this with your work.

Unfortunately not all keyboard layouts are the same... Latin American layout have '|' as the character above the tab and worse is that for Latin American layout to type '\\' or '`' one needs to press Alt Gr (which is right Alt) which is the least used modifier in use (left like left Ctrl). 

Also when I type '\\' it doesn't show all extensions but typing ';' does work. Unfortunately due how Gnome handles Latin America typing when I press Alt Gr + ] key in order to type '`' Gnome doesn't type that character immediately but waits for another key to be pressed. If such a key is a vocal it might do a accent like 'à' or 'è' and if it is a consonant just that '``f' and as you can see not ideal as typing those wont show all extensions. 
As it is now I can only search for all extensions using ';' and noting else due to the limitations to Gnome handling the Latin American layout.

Thank you so much for the time to read this and the great work in this extension. Have a great day!

**Comment by G-dH** [comment]
Thanks for the feedback. For now, only those three prefixes (; ` eq//) are supported. I can add more of course. However, it has to be a character that is not common in the results of other search providers, in order to filter out their results.

**Comment by G-dH** [comment]
`|` added.
